# Generated by Django 5.2.7 on 2026-01-01 14:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('calories_per_100g', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='meal',
            name='calories_per_100g',
        ),
        migrations.AlterField(
            model_name='meal',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meal',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.food'),
        ),
    ]
