# Generated by Django 5.2.7 on 2026-01-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_food_remove_meal_calories_per_100g_alter_meal_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='quantity',
            new_name='quantity_in_grams',
        ),
    ]
