# Generated by Django 5.2.7 on 2025-12-09 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_fooditem_food_name_fooditem_calories_per_100g_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealitem',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.fooditem'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.meal'),
        ),
    ]
